import { getTodayPlus } from "../utils/date";

export const FONT_URL = "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap";

export const STAGES = [
  { id: "new",             label: "New Lead",                                    color: "#6366f1", light: "#eef2ff" },
  { id: "call1",           label: "First call + SMS",                            color: "#3b82f6", light: "#eff6ff" },
  { id: "call2",           label: "Second call + SMS",                           color: "#60a5fa", light: "#dbeafe" },
  { id: "call3",           label: "Third call + SMS",                            color: "#818cf8", light: "#e0e7ff" },
  { id: "video_sent",      label: "Video Sent",                                  color: "#a855f7", light: "#f3e8ff" },
  { id: "trash",           label: "Trash / Cold",                                color: "#94a3b8", light: "#f1f5f9" },
  { id: "ppw",             label: "Waiting for PPW",                             color: "#f59e0b", light: "#fffbeb" },
  { id: "beenverified",    label: "BeenVerified Checked",                        color: "#f97316", light: "#fff7ed" },
  { id: "videocall",       label: "Videocall planned",                           color: "#06b6d4", light: "#ecfeff" },
  { id: "offer_sent",      label: "Offer Sent",                                  color: "#10b981", light: "#ecfdf5" },
  { id: "offer_accepted",  label: "Offer Accepted",                              color: "#059669", light: "#d1fae5" },
  { id: "drug_test",       label: "Pre-employment Drug Test (waiting result)",   color: "#eab308", light: "#fefce8" },
  { id: "set_date",        label: "Need to set up date to arrive yard",          color: "#14b8a6", light: "#f0fdfa" },
  { id: "yard",            label: "Waiting at the yard",                         color: "#0ea5e9", light: "#f0f9ff" },
  { id: "hired",           label: "Hired",                                       color: "#16a34a", light: "#f0fdf4" },
  { id: "fired",           label: "Fired",                                       color: "#ef4444", light: "#fef2f2" },
];

export const DOC_LIST = [
  "CDL Copy",
  "MVR Report",
  "PSP Report",
  "Drug Test Consent",
  "Employment Application",
  "Prev. Employment Verification",
  "Medical Certificate (DOT)",
  "SSN / Work Authorization",
  "Background Check",
];

export const SOURCES = ["Indeed", "CDLjobs", "Referral", "LinkedIn", "Cold Call", "Other"];

export const TEXT_TEMPLATES = [
  {
    label: "First Contact",
    body: "Hi [NAME], this is [RECRUITER] from [COMPANY]. I saw your profile on [SOURCE] - we're hiring Class A CDL drivers in [REGION]. Pay is [RANGE]. Available for a quick 5-min call today?",
  },
  {
    label: "No Answer Follow-up",
    body: "Hey [NAME], tried reaching you - [RECRUITER] from [COMPANY]. We have an opening matching your experience. Reply YES and I'll send details, or call me at [PHONE].",
  },
  {
    label: "App Reminder",
    body: "Hi [NAME], [RECRUITER] here. Did you get a chance to start the application? Here's the link again: [LINK]. Let me know if you have questions!",
  },
  {
    label: "Docs Reminder",
    body: "Hi [NAME], we're almost done with your file! We just need [MISSING DOC]. Can you send it to [EMAIL] today so we can move forward?",
  },
  {
    label: "Offer Follow-up",
    body: "Hi [NAME], following up on our offer. We'd love to have you on the team! Any questions I can answer? Looking to get paperwork started this week.",
  },
  {
    label: "Re-engage Cold",
    body: "Hi [NAME], [RECRUITER] from [COMPANY] - we spoke a few weeks back. We have a new opening that might be a better fit. Still looking? Takes 2 min to chat.",
  },
];

export const CALL_LOG_TPL = `Date/Time: [DATE] [TIME]\nType: [Call / Text / Email / Voicemail]\nDuration: [X min]   Spoke To: [Yes / No]\n------------------------------\nSUMMARY:\n[What was discussed]\n\nKEY POINTS:\n- CDL Class:            - Experience:\n- Available:            - Interest: [Hot/Warm/Cold]\n- Objections:\n\nNEXT ACTION: [What + When]`;

export const FLAGS_OPT = [
  "DUI / Major Violation",
  "Gaps in Employment >6 months",
  "Multiple jobs in last 2 years",
  "Failed drug test history",
  "Referral (priority)",
  "No-show / ghosted",
];

export const SAMPLE_DRIVERS = [
  {
    id: 1,
    name: "James Miller",
    phone: "555-0101",
    email: "j.miller@email.com",
    city: "Chicago, IL",
    cdl: "A",
    exp: 7,
    source: "Indeed",
    stage: "qualified",
    nextAction: getTodayPlus(0),
    nextActionTime: "10:00",
    lastContact: getTodayPlus(-1),
    docs: { "CDL Copy": true, "MVR Report": true },
    notes: [],
    files: [],
    flags: [],
    interest: "Hot",
  },
  {
    id: 2,
    name: "Robert Davis",
    phone: "555-0102",
    email: "r.davis@email.com",
    city: "Dallas, TX",
    cdl: "A",
    exp: 3,
    source: "CDLjobs",
    stage: "contact",
    nextAction: getTodayPlus(-1),
    nextActionTime: "09:30",
    lastContact: getTodayPlus(-2),
    docs: {},
    notes: [],
    files: [],
    flags: ["Gaps in Employment >6 months"],
    interest: "Warm",
  },
  {
    id: 3,
    name: "Michael Brown",
    phone: "555-0103",
    email: "m.brown@email.com",
    city: "Phoenix, AZ",
    cdl: "A",
    exp: 12,
    source: "Referral",
    stage: "application",
    nextAction: getTodayPlus(0),
    nextActionTime: "14:00",
    lastContact: getTodayPlus(0),
    docs: { "CDL Copy": true },
    notes: [],
    files: [],
    flags: ["Referral (priority)"],
    interest: "Hot",
  },
  {
    id: 4,
    name: "William Wilson",
    phone: "555-0104",
    email: "w.wilson@email.com",
    city: "Houston, TX",
    cdl: "B",
    exp: 2,
    source: "Indeed",
    stage: "new",
    nextAction: getTodayPlus(0),
    nextActionTime: "11:00",
    lastContact: null,
    docs: {},
    notes: [],
    files: [],
    flags: [],
    interest: "Warm",
  },
  {
    id: 5,
    name: "David Martinez",
    phone: "555-0105",
    email: "d.martinez@email.com",
    city: "Miami, FL",
    cdl: "A",
    exp: 5,
    source: "LinkedIn",
    stage: "docs",
    nextAction: getTodayPlus(2),
    nextActionTime: "15:30",
    lastContact: getTodayPlus(-1),
    docs: {
      "CDL Copy": true,
      "MVR Report": true,
      "PSP Report": true,
      "Drug Test Consent": true,
    },
    notes: [],
    files: [],
    flags: [],
    interest: "Hot",
  },
  {
    id: 6,
    name: "John Anderson",
    phone: "555-0106",
    email: "j.anderson@email.com",
    city: "Atlanta, GA",
    cdl: "A",
    exp: 9,
    source: "CDLjobs",
    stage: "offer",
    nextAction: getTodayPlus(1),
    nextActionTime: "13:00",
    lastContact: getTodayPlus(0),
    docs: {
      "CDL Copy": true,
      "MVR Report": true,
      "PSP Report": true,
      "Drug Test Consent": true,
      "Employment Application": true,
    },
    notes: [],
    files: [],
    flags: [],
    interest: "Hot",
  },
  {
    id: 7,
    name: "Thomas Taylor",
    phone: "555-0107",
    email: "t.taylor@email.com",
    city: "Denver, CO",
    cdl: "A",
    exp: 4,
    source: "Cold Call",
    stage: "cold",
    nextAction: getTodayPlus(14),
    nextActionTime: "10:00",
    lastContact: getTodayPlus(-10),
    docs: {},
    notes: [],
    files: [],
    flags: ["No-show / ghosted"],
    interest: "Cold",
  },
];
