[build]
  command = "echo no build needed"
  publish = "public"

[functions]
  directory = "netlify/functions"

[functions."call-stats-midday"]
  schedule = "0 16 * * *"

[functions."call-stats-digest"]
  schedule = "0 23 * * *"

[functions."call-stats-chronic-alert"]
  schedule = "0 12 * * *"

[functions."call-stats-digest-group-9am"]
  schedule = "0 13 * * *"

[functions."call-stats-digest-group-1pm"]
  schedule = "0 17 * * *"

[functions."call-stats-digest-group-4pm"]
  schedule = "0 20 * * *"

[functions."call-stats-snapshot"]
  schedule = "*/30 * * * *"
